from . import account_analytic_line
from . import hr_attendance
from . import hr_employee
from . import hr_field_device
from . import hr_field_face
from . import hr_field_manual
from . import hr_field_timesheet_list
from . import hr_field_roster
from . import hr_field_service
from . import project_project
from . import hr_field_day
